#include "make_credential.h"

/*
When such a request is received, the authenticator performs the following procedure:
    1. If the excludeList parameter is present and contains a credential ID that is present on this authenticator, terminate this procedure
    and return error code CTAP2_ERR_CREDENTIAL_EXCLUDED.
    2. If the pubKeyCredParams parameter does not contain a valid COSEAlgorithmIdentifier value that is supported by the authenticator,
    terminate this procedure and return error code CTAP2_ERR_UNSUPPORTED_ALGORITHM.
    3. If the options parameter is present, process all options and if any of the requested options can't be satisfied, terminate this
    procedure and return the CTAP2_ERR_OPTION_NOT_SUPPORTED error.
    4. Optionally, if the extensions parameter is present, process any extensions that this authenticator supports. Authenticator extension
    outputs generated by the authenticator extension processing are returned in the authenticator data.
    5. If pinAuth parameter is present and pinProtocol is 1, verify it by matching it against first 16 bytes of HMAC-SHA-256 of
    clientDataHash parameter using pinToken: HMAC-SHA-256(pinToken, clientDataHash).
    If the verification succeeds, set the "uv" bit to 1 in the response.
    If the verification fails, return CTAP2_ERR_PIN_AUTH_INVALID error.
    If pinAuth parameter is not present and clientPin been set on the authenticator, return CTAP2_ERR_PIN_REQUIRED error.
    6. If the authenticator has a display, show the items contained within the user and rp parameter structures to the user. Alternatively,
    request user interaction in an authenticator-specific way (e.g., flash the LED light). Request permission to create a credential. If the
    user declines permission, return the CTAP2_ERR_OPERATION_DENIED error.
    7. Generate a new credential key pair for the algorithm specified.
    8. If "rk" in options parameter is set to true:
    If a credential for the same RP ID and account ID already exists on the authenticator, overwrite that credential.
    Store the user parameter along the newly-created key pair.
    If authenticator does not have enough internal storage to persist the new credential, return
    CTAP2_ERR_KEY_STORE_FULL.
    9. Generate an attestation statement for the newly-created key using clientDataHash.
*/

int authenticator_make_credential_handler(app_ctx_t *ctx)
{
    // TODO: implement makeCredential logic

    /* 1. 
    */

    return 0;
}


