#ifndef CORE_STATE_MACHINE_APP_EVENTS_H_
#define CORE_STATE_MACHINE_APP_EVENTS_H_

typedef enum
{
    EVENT_MESSAGE_RECEIVED,
    EVENT_PAYLOAD_RECONSTRUCTED,
    EVENT_PROCESSING_DONE,
    EVENT_PAYLOAD_DECONSTRUCTED,
    EVENT_MESSAGE_SENT,
    EVENT_ERROR_OCCURED
} app_event_t;

#endif