#ifndef CORE_ERROR_MAPPER_ERROR_DOMAINS_H_
#define CORE_ERROR_MAPPER_ERROR_DOMAINS_H_

typedef enum
{
    ERROR_DOMAIN_NONE = 0,
    ERROR_DOMAIN_CTAP2_PARSER,
    ERROR_DOMAIN_CTAP2_PROCESSOR,
    ERROR_DOMAIN_CRYPTO,
    ERROR_DOMAIN_STORAGE,
    ERROR_DOMAIN_TRANSPORT
} error_domain_t;

#endif